### ISSUE TITLE
Executable version management

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#101]
We need to come up with a smart way to connect our "made up" Github release version numbers to the executable version number that we get via `Assembly.GetExecutingAssembly().GetName().Version`.

For example, for the PDF prints, I use the executable version.

**Comment by josegomez** [comment]
@alexhauser 
Hmmm The version in GitHub we have full control of we can make them match easily enough.
Why do you need the version number for the PDF ?
Also when sqrl is installed there is a version file created along with it you could read that one ?

**Comment by alexhauser** [comment]
@josegomez 

>Why do you need the version number for the PDF ?

I'm printing the executable version and creation date in the footer of the PDF, so that if later on a user has troubles with his identity, we know exactly when it was created and what the app version was. This will help in case we have bugs fixed in version xyz but the user still has a printed identity from version xya. That kind of thing.

>Hmmm The version in GitHub we have full control of we can make them match easily enough.

Sure, I just thought it would be great if we had one single place for changing version information that would then propagate to all the places where we need it (e.g. changing the `<AssemblyVersion>x.x.x.x</AssemblyVersion>` in the project file would take care of the rest). 

>Also when sqrl is installed there is a version file created along with it you could read that one?

Yeah, I can read the version from there, but where do I set it?

Thoughts?

**Comment by alexhauser** [comment]
@josegomez, thinking a little more about this, I think we should ditch the external file and use the executable version instead. There are a few reasons for that:

- The file is only there if the app was installed by the installer, so no "design time" support. Using the `<AssemblyVersion>x.x.x.x</AssemblyVersion>` in the project lets us track the version in Git and have it always available for reading AND writing.
- The version file might be a security issue, especially the way it is handled right now, where the update check returns false (no update available) if it cannot find the file. We should avoid this.
- Checking the assembly version from the installer instead of the file should be as easy as

```C#
Assembly assembly = Assembly.LoadFrom("SQRLDotNetClientUI.exe");
Version ver = assembly.GetName().Version;
```
What do you think?

**Comment by josegomez** [comment]
Fair enough how do we set that version number consistently?

**Comment by alexhauser** [comment]
Ok, here's a suggestion:

Let's use Github's "milestones" feature. For each planned release, we create a milestone. As soon as we've pubslished a release, we create a new milestone, representing the "next version" for the app. In between releases, we can increment the revision (the last number of the version, so for example 0.1.1.**2**) if we want.

For example, since we're now on 0.1.1 beta 3, I've added a milestone `v0.1.2`, and linked some issues with the milestone. https://github.com/sqrldev/SQRLDotNetClient/milestone/1

When eventually all the issues/PRs associated with that milestone are solved/implemented, we set the corresponding assembly version through the project properties in VS or manually in the project file and this commit is than tagged with that version number and released on Github.

What do you think?

**Comment by josegomez** [comment]
Sounds good @alexhauser

**Comment by alexhauser** [comment]
Cool, @josegomez!

So next milestone is 0.1.2, if you have other issues that you want to see in that milestone, just add them. Once we got all of those tackled, we can prepare the next release.

Let's only close this issue once we've baked this into the installer/version check though.

**Comment by alexhauser** [comment]
@josegomez, just so that we're on the same page, the assembly version gives us 4 "sets" of numbers for the version string, e.g. `0.1.2.3` .

I'd suggest to (loosely) follow the following convention (taken from StackOverflow):

> MAJOR.MINOR.REVISION.BUILDNUMBER, where MAJOR is a major release (usually many new features or changes to the UI or underlying OS), MINOR is a minor release (perhaps some new features) on a previous major release, REVISION is usually a fix for a previous minor release (no new functionality), and BUILDNUMBER is incremented for each latest build of a revision.

As you might have seen, I've edited the last 2 Github release tags to follow the x.x.x.x notation. The consequence is that now the app thinks a new version is available. That's because there is no actual "higher version check" implemented right now, only a "is the current tag different to what's the latest on Github".

Do you want to update that code, since it's your baby? Or do you want me to do it? 🤗

**Comment by josegomez** [comment]
@alexhauser feel free to update it I'm buried at work today so if you got the time go for it 😊
