### ISSUE TITLE
[all] Enhance Dialog "feature" to use AutoResetEvent?

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#114]
Hi @alexhauser  I just saw you used an AutoReset event in your latest "dialog" replacement. I didn't know about this feature of the threading library so when I implemented the other dialogs I used a BlockingCollection instead to block the thread while waiting for the user.

May be worth to go fix those and use the AutoReset instead? BlockingCollection is nice but its way over-kill for these.
I think ¯\\_(ツ)_/¯

**Comment by alexhauser** [comment]
Yeah @josegomez, it would at least have been overkill for my task, because I didn't even need to pass around data or return anything. `AutoResetEvent` is nice in terms of its slim syntax and (hopefully) low overhead.
