### ISSUE TITLE
[all] Enhance Export to Include Block1 (choice)

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#116]
Steve's client allows you to export either block2 and 3 only or "for convenience" include block1
![image](https://user-images.githubusercontent.com/420837/79466714-f0e6cb80-7fca-11ea-9a54-7f41ca9f14a7.png)

Just ran into an issue while testing the IOS app that it doesn't support importing block2 and 3 only (yet) now this is a shortcoming of that app, but since steve included this option in his client, maybe so should we.

Thoughts? @alexhauser ?

**Comment by alexhauser** [comment]
Yep @josegomez, we should definitely add support for that!

**Comment by alexhauser** [comment]
I'll take this one next, @josegomez!

**Comment by josegomez** [comment]
Sounds good @alexhauser, I'm about to push the CPS one sorry it took so long, work has been kicking my rear end.

**Comment by alexhauser** [comment]
No need to rush @josegomez, it's not like we have to meet a deadline or anything! 😅
