### ISSUE TITLE
[Linux] Idle timeout seems to be broken

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#126]
While testing on Linux, I noticed log messages regarding idle timeout being hit, even though the timeout in the loaded identity was set to 15 minutes. It seems that the idle timeout is consistently hit after about 5 seconds. Something seems broken here.

**Comment by josegomez** [comment]
yeah I noticed this too forgot to make an issue thanks @alexhauser

**Comment by josegomez** [comment]
I'll take this @alexhauser

**Comment by josegomez** [comment]
Fixed by #129
