### ISSUE TITLE
[library] Add Logging to SQRL Library

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#127]
Currently SQRL Library has no logging, may be useful to add Sirilog support there too.

**Comment by alexhauser** [comment]
Yeah, it would certainly be useful, although I'm not quite sure on how to handle this for a library that is supposed to be used by other parties that might have a completely different logging system/approach/need.

But as long as it can be turned off, it should not really matter too much.

Also, we'll need to be extra careful not to accidently log any sensitive information such as keys, seeds, nonces etc.

**Comment by alexhauser** [comment]
Working on this one right now, @josegomez!
