### ISSUE TITLE
Add Logging

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#13]
We should add logging capabilities (everywhere) it is getting harder and harder to debug issues particularly outside of Visual Studio having logging built in would be nice.

DotNetCore supports logging Factory so something in that vein one of the providers. Maybe Serilog? IDK just adding this issue for tracking purposes.

**Comment by alexhauser** [comment]
Serilog looks good and seems to have a very clean API, so no objections here.

**Comment by alexhauser** [comment]
@josegomez, just letting you know that since I will need solid logging to be in place for the QuickPass feature implementation, I am going to integrate Serilog support along with the QuickPass implementation.

**Comment by josegomez** [comment]
Awesome @alexhauser
