### ISSUE TITLE
Improve CPS Startup Time add CPS Event

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#130]
In #102 the point was raised that we could "AWAKEN" the UI from CPS if we start CPS right away when the client launches and have it running.

When a CPS request is received we could trigger an awake command and rouse the client to the foreground and initiate an Authentication request right there without having to rely on the sqrl:// scheme invocation. This would shorten the Auth time for requests that come in if the client is already running.

Currently we launch another instance of SQRL and use the Mutex and IPC for communication which comes at a significant overhead.

With our current Implementation of CPS we do not start CPS listening until an Auth request is recveived so this would have to change.

Further more we would have to implement an Event (CPSReceivedEvent) in the SQRL library to have the UI client subscribe to and be awakened from since the SQRL/CPS are in a separate and unrelated project and library that is not aware (nor should it be) about the Client.

We could then subscribe to this event from the Client and raise the app when a CPS request is received.

My main concern about this is the fact that we would introduce a race condition whereby the sqrl:// invocation and the CPS Event would "Race" to figure out which one handles the AuthRequest and we would have to find a way to handle that via the ICP process.

Perhaps we abort the ICPProcess invocation if an Auth request is currently in process?

This is more of a question than a //TODO 

Thoughts @alexhauser ?

**Comment by alexhauser** [comment]
@josegomez, I'll have to think about this some more, I'll get back to you on that!

**Comment by dxcSithLord** [comment]
Some more thoughts to consider :
Found this for windows IPC, which can also be used on *nix, [https://docs.microsoft.com/en-us/windows/win32/ipc/interprocess-communications#using-pipes-for-ipc](https://docs.microsoft.com/en-us/windows/win32/ipc/interprocess-communications#using-pipes-for-ipc)  The pipe can be opened by the client that is running first.  Attempts to open the "read" or receiving end would fail on subsequent attempts (new instances), that can then open the "write" end of the pipe and send the information to the already running process.  Alternatively, sockets are also available cross platfom, also referenced in the same article.  Note MacOS is derrived from BSD, which is where Windows sockets came from.   Apologies if you are already aware of this, but thought this an alternative to port 13000, especially if it is available across all platforms.

**Comment by josegomez** [comment]
@dxcSithLord just curious as to what you don't like about the current IPC solution? It is clean and a single code tree for all platforms. What don't you like about it?

**Comment by josegomez** [comment]
Looking at the implementation Anonymous-pipes it isn't any simpler than a simple TCPClient

![image](https://user-images.githubusercontent.com/420837/79786720-e6eb0280-8313-11ea-901a-22efeff5ef6c.png)

**Comment by alexhauser** [comment]
> @dxcSithLord just curious as to what you don't like about the current IPC solution? It is clean and a single code tree for all platforms. What don't you like about it?

I was about to ask the same thing.

**Comment by dxcSithLord** [comment]
It's not that I don't like it, I just want to understand that others have been considered.  If this is the best, then that is good, but it can only be the best, if/when others have been considered and rejected for a good reason.  The reason could be security, or just incompatibility across platforms.
For example, how was port 13000 chosen?  Does this clash with ANY other program that could also be listening on port 13000 (current or future)?  How can you guarantee that this would never happen?  How is this interface protected/secured from bad input?
Semaphore : Where does the semaphore file get put?  What would the permissions be?
PIPE : How do you handle named pipes across different platforms, would this be more trouble than the benefit?
Sorry if I ask difficult questions, but asking them near the start is cheaper in time/cost/development/support in the long term than an incident raised later.  I have been bitten before by issues where the questions haven't been asked.  Make a choice, with good, well defined reasons and it can be defended.  edit: I also missed @josegomez 's comment earlier about use of semaphores.

**Comment by dxcSithLord** [comment]
On the other point on protocol handlers, see [https://unix.stackexchange.com/questions/497146/create-a-custom-url-protocol-handler](https://unix.stackexchange.com/questions/497146/create-a-custom-url-protocol-handler).
When the SQRLDotNetUI is installed is mentions about setting the sqrl association, but I cannot see the file either in ~/.local/share/applications/ or /usr/share/applications/.  Where would you expect the file to get put?  I will test the custom url protocol handler with a made up protocol "fred", so it doesn't clash with SQRL, hopefully tomorrow.

**Comment by josegomez** [comment]
@dxcSithLord See below, no worries regarding difficult questions we are just trying to understand where you are coming from so we can have a productive dialog. We appreciate your feedback

**How was port 13000 chosen? :**
At random there are a few things that run there but its mostly malware
https://www.speedguide.net/port.php?port=13000
We could make this configurable easily enough though now that we have app settings. @alexhauser 

**How can you guarantee that this would never happen?** 
You can't, but also can't guarantee that 22519 isn't going to clash. We are at the mercy of the user though as stated above our IPC port could be dynamic

**How is this interface protected/secured from bad input?**
Currently there isn't a ton of effort into this, though we could look into it I'll open an issue. It listens only on 127.0.0.1 not on the external interface so only something already running your system would be able to interact. But I'm sure we could harden it.

**Where does the semaphore file get put? What would the permissions be?**
This is handled via Microsoft's Implementation of [Mutex](https://docs.microsoft.com/en-us/dotnet/api/system.threading.mutex?view=netcore-3.1)
See Program.cs Line 27+
I'm not sure where the file is put, it is a specific implementation per system and microsoft takes care of it


**How do you handle named pipes across different platforms, would this be more trouble than the benefit?**
I looked at this briefly before settling in the TCP solution, named pipes are supported by most OS's but the implementation and supported methods vary, also there are permission issues particularly on Windows after Vista where Named Pipes require admin rights to function correctly (though there are workarounds)
If you have better information on this approach that makes it simpler and we can used seamlessly across platforms we are all ears.

**Comment by dxcSithLord** [comment]
That is what I wanted to see.  Can you put this description in a design document somewhere?  Thank you.  I will have a look at the code later.

**Comment by alexhauser** [comment]
@josegomez, I'm going for this one next!

I'll try to implement it the way the GRC client does it, with CPS constantly listening, and come up with a way to synchronize CPS and sqrl:// scheme invocation to avoid a race condition.
