### ISSUE TITLE
Move DB and Logging to User Space

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#133]
See: https://sqrl.grc.com/threads/windows-testing-feedback.1112/post-9418

I think I agree we should move the DB to user space 
Thoughts @alexhauser ?

**Comment by alexhauser** [comment]
Yes, totally!

**Comment by josegomez** [comment]
@alexhauser thinking about this from a design / "upgrade" path here's what I came up with

- Update the Platform Installer to detect / check if sqrl.db exists in the current install location (already does this to avoid overwriting)

- If the sqrl Db is found move it to the new location of our choosing (or add the ability for the user to provide a location where they want it stored... think keeping the db in dropbox or something like that?)
- Move the Db to the chosen location and write this location down in the config file (in the client install path)
- From the client side, read the db location from the appconfig file if it exists, use the Db from that location, if it doesn't fall back to the old sqrl.db in the local directory
- Add a setting/menu for moving , changing the Db location / Db File manually (think pulling a Db down from archive)

This would accomplish a few things, provide an "upgrade" path for the existing installations and also give us a way to dynamically change or move the Db file (as a setting) from the client
This should satisfy the permissions issue and make this install more portable.
Thoughts?

**Comment by alexhauser** [comment]
That sounds like a good plan, @josegomez ! 
Go ahead!

**Comment by alexhauser** [comment]
@josegomez, thinking about this some more, I'm not even sure if we should fall back to the install directory at all. Default (or user-chosen) location, and if that doesn't exist, just offer creating a new db somewhere in the userland. This would seem a little cleaner to me. Thoughts?

**Comment by josegomez** [comment]
Agreed

**Comment by josegomez** [comment]
@alexhauser Working on this one.

**Comment by josegomez** [comment]
So just as an FYI I just discovered that the Migrate() call on App.cs generates a new DB if the DB doesn't exist.. Which is pretty damn cool
