### ISSUE TITLE
Have the client update the installer

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#136]
We still need to implement the feature of the client being able to update the installer.

**Comment by josegomez** [comment]
Actually I already took care of this kind of 
The installer can be included in the app zip and gets extracted when the update happens 

Currently workflow 
Installer downloads zip and extracts it and copies itself into the install location (if the zip file didn’t contain a newer copy)

So basically every new version we want to update the installer we just need to make sure it’s included in the app zip

**Comment by alexhauser** [comment]
Ah, I wasn't aware, this is great @josegomez! 

Fyi, I'm working on an update to the `GithubAPI` project that would ignore releases where the release-tag contains the word "test" if a file named "TESTING" is present in the executable's directory. This should help us in testing the installation of new updates before they are being offered to "regular" client users. I'll post a PR shortly.
