### ISSUE TITLE
Bump version to 0.1.2.0, test and release

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#146]
### Description:

- [x] Resolve all open issues for milestone [v0.1.2.0-beta](https://github.com/sqrldev/SQRLDotNetClient/milestone/1)
- [x] Bump assembly version to 0.1.2.0
- [x] Release v0.1.2.0-beta by closing the milestone and activating @josegomez's fancy Github workflow.
- [x] Perform some thorough testing

**Comment by josegomez** [comment]
I'm going to setup a clean windows VM for testing the windows install and a clean Ubuntu VM you just setup your mac any chance you took a snapshot before you installed gdiplus and such?

Once we merge this final issue that's in the PR maybe  we can close the milestone build out the installer and test it in the clean VM's before we release?

**Comment by alexhauser** [comment]
> ... you just setup your mac any chance you took a snapshot before you installed gdiplus and such?

That's exactly what I did ;-)

> Once we merge this final issue that's in the PR maybe we can close the milestone build out the installer and test it in the clean VM's before we release?

Sounds like a plan. I'm gonna post a PR that sets the corresponding version number for the client as well as for  the installer assemblies. This should be the last merge before closing the milestone.

**Comment by alexhauser** [comment]
@josegomez, with #153 merged, I think we can close the milestone and start testing, right?

**Comment by josegomez** [comment]
Yes

**Comment by josegomez** [comment]
GitHub API is being stupid still I think so we’ll see if the assets get loaded
