### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#15]
All the UI strings are currently hardcoded in English. While this is fine for this early stage of development, we should definitely add localization support at some point, before it gets out of hand.

Is there any "standard" way to approach localization in .NET Core?

**Comment by josegomez** [comment]
Yup See
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization

**Comment by josegomez** [comment]
@alexhauser  added support for localization, now we need to create the strings and update all the xaml See PR #16 16

**Comment by alexhauser** [comment]
Nice, Jose, I will look into this as soon as I find some time!

**Comment by CreateLab** [comment]
May U share link to file with localozation and I help with ru-Ru

**Comment by alexhauser** [comment]
@CreateLab, thanks for your offer of helping out with the transalation and sorry for the late reply. 

We've been a little sluggish regarding the localization topic, since we've been concentrating on getting the client and library feature complete. Once localization support is up though, we'll be glad to point you to the necessary resources.

**Comment by CreateLab** [comment]
> @CreateLab, thanks for your offer of helping out with the transalation and sorry for the late reply.
> 
> We've been a little sluggish regarding the localization topic, since we've been concentrating on getting the client and library feature complete. Once localization support is up though, we'll be glad to point you to the necessary resources.

Ok, if need help, link me

**Comment by alexhauser** [comment]
@josegomez, I'm in the process of adding proper localization support to my latest contributions, but I ran into a problem:

While playing around with adding a German translation, I found that the localization extension you've added doesn't seem to properly handle the German special characters like `ä, ü, ö ...` etc:

![umlaut_error](https://user-images.githubusercontent.com/4005543/75115883-2faf7380-5663-11ea-9501-8bc6ed7c1dff.JPG)


I'm sure this just an encoding issue, but haven't had any luck trying quick fixes that came to mind like forcing the `StreamReader` that reads the json file to use `UTF8`.

Any ideas?

**Comment by alexhauser** [comment]
Nevermind @josegomez, I just found that the json file was encoded in ANSI - how weird ist that?! Converted it to UTF-8 and everything is fine now!

**Comment by josegomez** [comment]
Sweet that's weird sorry I've been afk this weekend

**Comment by alexhauser** [comment]
@CreateLab, the latest PR added full localization of the client project, so if you are interested in providing a translation, you can do so by adding it to this file:

https://github.com/sqrldev/SQRLDotNetClient/blob/master/SQRLDotNetClientUI/Assets/Localization/localization.json

**Comment by alexhauser** [comment]
@josegomez, I'm going to close this one for now as the main work for enabling continuous localization of the client is done. If we avoid using any hardcoded strings from now on, this should be it. 

For the future, we could think about using something like https://poeditor.com/ to enable community translations. But I think we should only do this once the client has settled to a state where changes to the language strings are not happening on a daily basis anymore.
