### ISSUE TITLE
[macOS] Minimize glitch

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#152]
### Description:
On macOS, "minimize to tray" isn't working, instead the app gets minimized to the dock, and when retstoring it from there (NOT from the tray icon), the main window is showing but is completely unresponsive. Only when selecting "restore" from the tray icon, the form gets accessible again.

@josegomez, do we want this fixed in 0.1.2.0 or shall we defer this to the next milestone?

**Comment by josegomez** [comment]
How intrusive is it @alexhauser ?

**Comment by alexhauser** [comment]
Well, I'm afraid a normal user will be kinda lost after minimizing the app once.

**Comment by josegomez** [comment]
Well if it’s that intrusive we’ll have to fix it 😑
