### ISSUE TITLE
[Installer]: Detect and fill in correct install path

### ISSUE THREAD

**Issue by dreamcat4** [sqrldev/SQRLDotNetClient#155]
Every time I run the updater, SQRL fills in the intall path as `/home/id/SQRL` however my local install of sqrl is not located there. That was just the default install path.

![](https://i.imgur.com/jIiHOWw.png)

So every time I update SQRL with the built in updater, I have to click the Install Path... button and re-navigate back to that folder.

The updater should be smart enough to work that bit out automatically. It should already know where SQRL has been installed on the system. The app is running from there!

Please try to fix this issue if you can. Many thanks.

//Edit by @alexhauser:
Issues to fix:
- [x] Remember installation path also when running the installer manually
- [x] Fix blindly appending "SQRL" to install path

**Comment by dreamcat4** [comment]
In fact there is another issue related to the manual selection of the install  update folder. Because the updater is not smart enough to see and detect the user already selected the `SQRL` folder itself. Rather than the parent folder. And it automatically then appends another `SQRL` subfolder tacks that onto the end there. This has caused my folder to then get screwed up with 2 copies of SQRL client installed there.

A smarter approach would be to add a routine that detected if there were already SQRL files in that parent folder and then intelligently not tack on the extra subfolder. Also (in addition) check if the parent folder's name is `SQRL` too. Or at least throw up some warning or notification message IDK.

**Comment by alexhauser** [comment]
Thanks for reporting, @dreamcat4!

The first issue (detecting a cusom installation path) should already be partly handled by #141, so next time the installer is run by the client detecting an update, it should be handled correctly. However, I think when running the installer manually, this might still be an issue, and we'll have to look into this.

The second point you raised (blindly appending `SQRL` to the install path) was already noticed by Jose yesterday after the release, so it's on our mental list of things to fix.

Even better that there's an issue for those things now!

**Comment by alexhauser** [comment]
@josegomez, I guess we'll have to find a way to remember the installation path.

On Windows, no big deal, we just create a registry entry for that. But how do we handle it on Linux and macOS? Anyone knows a "standard compliant" way of doing it on those platforms?

**Comment by alexhauser** [comment]
Just posted a PR for the second part of this issue, see #157.

**Comment by dreamcat4** [comment]
Glad to hear its already getting looked at... and oh yeah sorry i forgot to mention this was occuring on linux. In case you need me to come back and test these intended fixes. to make sure its also working for that platform. Thank you.

**Comment by dxcSithLord** [comment]
The standard way to remember stuff on *nix is to set up an environment variable, which can either be system wide and refer to the user $HOME directory for individual locations, or can be overridden by an individuals file in their own home directory, that defines a different path.  Depending on the shell environment, the variables would be set up in slightly different files.  Ubuntu (which uses BASH - "Born Again SHell") and the files that would hold this information are in /etc/bash.bashrc, with personal localisation in ~/.bashrc for non-interactive shell invocations.  (see manual for BASH, specifically sections 5 and 6 [https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Shell-Variables](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Shell-Variables) for more detail.
The variables could also be located in the previously install SQRL folder, e.g. sqrl_env.sh would be an appropriate file name - the ".sh" is only for humans, won't make any difference with or without.  The first line should be :`#!/bin/bash ` which defines what is in the file and what should invoke it.

**Comment by alexhauser** [comment]
@dxcSithLord, environment variables are the obvious choice, but they have their own set of problems, the most important of them being that they are shell-dependant. Not everyone uses Bash.

However, if we don't find a better solution that works across all distros and shells, I guess we're pretty much stuck with envirnoment variables.  Placing a shell script in `/etc/profile.d` seems to be the preferred way in modern Linux distros though.

Thoughts? @josegomez  @dxcSithLord, @dreamcat4

**Comment by dreamcat4** [comment]
Hmm. Well if you save some path to `/etc/profile.d` then presumably you cannot have multiple per-user installs of SQRL on the system. Well that could be an issue if there is a user who installed it as a per-user program inside their `$HOME` folder. Then you are writing that location into `/etc/` is maybe not the right thing to do. At least on multi user UNIX platforms. What would be better is to have that instance of SQRL client being updated be able to pass on it's own location without needing to involve anybody else.

> On Windows, no big deal, we just create a registry entry for that. But how do we handle it on Linux and macOS? Anyone knows a "standard compliant" way of doing it on those platforms?

The FreeDesktop project uses a variety of `XDG_` environment variables to determine the default path. However what I am guessing you are talking about is having some type of communication between the exited SQRL client program, which should know its location (before the user hit 'update' button). And then the launched SQRL installer program.

Well there are a whole variety of methods that could be used. And it's not really clear which is best for you guys to me, since you are using .NET frameworks for the multiplatform aspect etc.

Potentially you are also trying to make this mechanism distro agnostic. So how do you launch the updater program from the SQRL client? Do you replace the existing running proc with a call to exec() ? Or rather does your call to whatever .NET lib api method do that? Then you should be able to pass in env variables to the new process without needing to write to some specific file on the disk. You just save to an env var and it can be passed in there to the new proccess. Or maybe you could accomplish a similar thing by passing with an argv[] array of cmdline flags.

Wheras if both of your processes are running at the same time, with a hand over period then you could use something else for example SHM, or a TCP socket, or a UNIX socket, or something else entirely different.

Unfortunately I don't know enough here to clearly tell you which method is simplest / best / most reasonable for your implementation. As my lack of knowledge of .NET some of those solutions would be more difficult to achieve than other ones. Depending upon what sort of official .NET APIs are being made available to you there in your C#.

There are probably also a few other reasonable ways I have at the moment forgotten about.

**Comment by dreamcat4** [comment]
Ah so this is the place it is doing that

https://github.com/sqrldev/SQRLDotNetClient/blob/master/SQRLDotNetClientUI/ViewModels/MainMenuViewModel.cs#L322-L371

**Comment by dreamcat4** [comment]
So what I don't understand here is why this is not [already passing the install target location as cmdline arguments here](https://github.com/sqrldev/SQRLDotNetClient/blob/master/SQRLDotNetClientUI/ViewModels/MainMenuViewModel.cs#L346) with the `Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)`...

or if that is not it then I would fully expect for .NET to let you to set any custom environement variables you wish on the `proc.StartInfo` object. And then you would have to add something in the installer program check for those env vars once it gets launched. To auto-fill the known location of the existing SQRL client. To make that the install folder. Am I missing something here?

Because if you do this then you should not need to resort to something like `/etc/profile.d`. Which is not really such a good idea.

**Comment by josegomez** [comment]
@dreamcat4 it does already pass it but that was a new enhancement that we added in this release.
So going forward it will do that when an update is found.
Unfortunately the installer will always be one version behind when the update runs 

Since we need to use the installer to download the next version 

So if we were to release another update now, then your installer would indeed pass the current location 

However this doesn’t address someone manually running the installer

**Comment by alexhauser** [comment]
@dreamcat4 you're probably right that exporting the env var from `/etc/profile.d` would not work well for a multi-user system and therefore isn't the right approach.

What we need is a way for setting a global, persistent, per-user, shell- and distro-agnostic environment variable that the installer can read when being launched manually.

**Comment by josegomez** [comment]
Haha what we need is a windows registry! Actually what we need is windows period 😜

**Comment by dreamcat4** [comment]
Ah ok sorry for not understanding earlier. The main thing to realize is that *NIX systems have evolved over many years. So there are multiple different mechanisms. Which all end up getting used for various different types of programs. So you have some choice to make which to acutally use, each mechanism has it's own different set of advantages and disadvantages. Depending on what you might prefer.

If you are angling at your program being some classic style X Windows program, with as few assumptions or external dependencies as possible. So that it can work pretty much everywhere, including really basic systems with stripped down window managers. Then there is the FreeDesktop XDG specification.

This will let you write a file into either `~/.config/somefolder`.. or into  `/etc/xdg/` folder for a global scope. However many programs don't actually respect `/etc/xdg` location and instead choose to write into the `etc` directory directly such as `/etc/SQRL/filename`. Or `/etc/sqrl.config` or something similar. Whichever the global config in `/etc/` would be pointing to the system wide location, which is going to be the fallback location when the per-user `$HOME/.config/...` config file was not found.

XDG specification is explained here:

https://unix.stackexchange.com/questions/312988/understanding-home-configuration-file-locations-config-and-local-sha

But if you do want something that is a lot more like the windows registry... then you may need to assume some external dependency on a newer systems. And this will assume certain packages installed coming from Gnome project. For example the `dconf` database. This is what we use on linux as our version of 'the registry' these days. For modern GUI programs. This then assumes that the linux system actually has a working dconf database that you can write to. 

https://en.wikipedia.org/wiki/Dconf

To make it easier to understand `dconf`, try the GUI Program `dconf editor` which if you install it on your linux distro locally it will provide an easy way to browse through your dconf database.

Now perhaps there is a way to also store default values in dconf for when there is no per-user setting written. So that the default system wide value can be used instead as a fallback or just simply the default. However I cannot remember how to you might achieve that. Sorry for being vague there!

It would seem that the typical package requirements for having a working dconf database on the system is a package named `dconf-service`, which then in turn requires `dbus`.

So you will usually find all that on most modern linux distros. However just be aware that it's an extra dependancy which you would not otherwise need to worry about if you used a config file in the XDG system.

Either way you should have to check the per-user location before checking the system wide location as a fallback. Unless the program was launched as root user (`uid=0`) in which case the global system wide location should probably be used instead as the preferred location.

So if a user ran their installer manually, the installer would check for these as a lower priority after the more important cmdline argument flags (or ENV variable) being passed into the installer process.

And use those found values to populate the 'install location' field plus any other saved installer settings. If there are other checkboxes that the user ticked / cleared on their original install. It would also make sense to remember what those were too and store that related config into the same place as the SQRL installed foder.

**Comment by alexhauser** [comment]
Thanks for elaborating @dreamcat4, very much appreciated!

Considering all the input above, I'd opt for using the lowest common denominator, which would be using the XDG spec and writing the install path into a file such as `$HOME/.config/sqrl/sqrl.conf`

What do you think, @josegomez?

**Comment by dreamcat4** [comment]
Of course what would be best here is if there were already some `.NET` apis or libraries which did all the heavy lifting for you. So that you didn't need to worry about how to handle these things yourselves.

I am not sure if already exists in .NET land libraries specifically for handling XDG configs. But that should be pretty simple and not different than reading / writing a config file from some specific location. So here is a generic guide for that:

https://ploum.net/207-modify-your-application-to-use-xdg-folders/

However in the case of Dconf database, there seems to be a way to call through existing C/C++ library from C#. So here is some dude who has already figured out how to achieve that:

https://blog.honosoft.com/2019/03/14/linux-dotnet-core-gsettings-libgio-directly-from-code/

Ah finally... there is in fact some DotNET library existing for doing that (accessing dconf database through gsettings dll / shared library):

https://github.com/Nordes/HoNoSoFt.LibGio.Bindings

So you can choose either methods... I make no judgements. Just I hope that by knowing what is required for each solution then that will help for you to decide. Good day.

**Comment by dreamcat4** [comment]
Ah-ha! Here is another useful (better!) resource for understanding the XDG folders and `~/.config` in unix. Acually written for Go Language but at least the README shows clearly what all the folders are etc.

https://github.com/adrg/xdg

...Have not found any equivalent library that will do that in DotNET. But it's still a good example of what I was looking for i guess? Just in the wrong programming language.

**Comment by dreamcat4** [comment]
SO yes if you are going XDG then read here https://github.com/adrg/xdg/blob/master/README.md

**Comment by alexhauser** [comment]
As it turns out, .NET Core already follows the XDG basedir spec on Linux.

For example, `System.Environment.SpecialFolder.ApplicationData` maps to `XDG_CONFIG_HOME`, which in turn defaults to `$HOME/.config`.

One more reason to use this approach I guess.

**Comment by dxcSithLord** [comment]
I haven't read everything since I was last here, but I think you have worked this out.  Note(if not already said) that the global settings would use $HOME for the users directory.  SQRLDotNet, could use 
$SQRLDotNet  = $HOME/SQRL
$SQRLDotNetDB = $SQRLDotNet/sqrl.db
as defaults and hence if the user did want to change the setting, they would only need change these variables to configure it.  This is a common approach for any application on Unix/Linux land.

**Comment by alexhauser** [comment]
Thanks for all the valuable input @dxcSithLord and @dreamcat4!

I think I have a better understanding of how to approach this now, looking forward to you guys/gals checking out what we'll come up with, probably in the upcoming version 0.1.3 release.

**Comment by alexhauser** [comment]
@dreamcat4, the next installer release will remember the installation path.

You'll still have to enter the correct path once more though, since we're not detecting a cusom install path that was set using an older version, sorry.
