### ISSUE TITLE
[Installer] Provide Uninstall Support (Platform Specific)

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#159]
We need to provide uninstall support
We should modify the installer to take a command line argument that tells it to uninstall
We need to modify the Windows version to add an entry in Add/Remove programs
For Linux / Mac maybe we add an entry in the Program Itself to invoke the uninstaller since there isn't really a standard
We need to update the installer to keep a "log" record of all files and entries (registry) it creates so that we can run through it during uninstall process.

**Comment by alexhauser** [comment]
@josegomez, I would like to suggst to adopt the implementation interface model that we have in the client (e.g. for `NotifyIcon` etc.) for the installer as well.

At the moment, we have methods like `InstallOnWindows()`, `InstallOnLinux()`, `InstallOnMac()` and the view models already become quite messy.

It would be nice if we just had an `IInstaller` interface that we could call `Install()` or `Uninstall()` on in the view model, and the platform specific "nitty-gritty" stuff is tucked away within their own platform-specific implementation of the `IInstaller` interface.

What do you think?

**Comment by josegomez** [comment]
Sounds good!

**Comment by alexhauser** [comment]
@josegomez, I would like to look at this one next.

**Comment by josegomez** [comment]
Perfect
