### ISSUE TITLE
[Linux] Garbled window contents after restoring from tray icon

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#160]
### Description:
As seen in our own testing, and now confirmed by a forum user, sometimes when restoring the main window from the tray icon on Linux, the window contents are garbled:

![VirtualBoxVM_2020-04-28_09-14-24](https://user-images.githubusercontent.com/4005543/80465614-a0ad2900-893b-11ea-8bba-e95e9f63214a.png)

Hitting "restore" again from the tray icon's menu usually fixes this. Sometimes, it also returns to normal by itself after a few seconds.

I guess we should look into this.

**Comment by josegomez** [comment]
Can confirm that this indeed NOT fixed in 0.9.9
Issue https://github.com/AvaloniaUI/Avalonia/issues/2994

Clicking anywhere on the screen or moving the screen around fixes this glitch BTW

**Comment by alexhauser** [comment]
Looks like it's getting fixed upstream.

**Comment by josegomez** [comment]
Sweet looks like there's a PR To Address it
https://github.com/AvaloniaUI/Avalonia/pull/3876

Hoping it will get merged soon and hopefully pushed on the next release of Avalonia

**Comment by alexhauser** [comment]
The PR mentioned above was just merged into master in Avalonia, so we should be able to get the fix for this issue with the next Avalonia release!

**Comment by josegomez** [comment]
0.9.10 Dropped this morning however looks like this merge didn't make it onto that one :'(

**Comment by alexhauser** [comment]
No, unfortunately it came in right after they released 0.9.10. 😥

**Comment by ghost** [comment]
More information about this bug. If you wait a few seconds after clicking the restore option of the SQRL icon in the top bar the correct information displays. It appears to be a delay in processing what information should be displayed.

**Comment by ghost** [comment]
MacNala is Alan M Cameron by a previous github signin.

**Comment by alexhauser** [comment]
@MacNala, thanks for reaching out. We've already found the root cause for the issue, and it's actually a problem in one of the libraries we use, so not directly related to our code. The good news is that there is already a fix coming, we'll just have to wait for the next release of the Avalonia UI library, wich should happen sometime in the beginning of June according to the devs there.
