### ISSUE TITLE
Linux/Ubuntu18.04.04/Firefox75.0 (64-bit) - UI crash when quick pass is used

### ISSUE THREAD

**Issue by dxcSithLord** [sqrldev/SQRLDotNetClient#166]
Compiled locally with latest and ran to test on upgraded Wordpress site via Firefox with test identity
1. cd ~/src/SQRLDotNetClient/SQRLDotNetClientUI
2.  git pull
3.  dotnet clean
4.  dotnet build
5.  dotnet run
GUI displayed.  Clicked on "Import identity".  Pasted in previous "test" identity, including hyphons.  Copied rescue code, including hyphons, removed the last two hyphons from the code (key press sequence CTRL&LEFT,DEL,CTRL&LEFT,DEL<RETURN>) and BY ACCIDENT hit return.  The identity was loaded - no password entered.  Previously, I had removed ALL the hyphons, since copying in the rescue code with hyphons didn't work, but hadn't tried missing SOME of them (that may be another issue).  Attempted to login to my wordpress site with latest wordpress upgrade, same problem with detecting SQRL://, but didn't work, so went back with the intention of removing and re-adding the identity, but on remove identity - prompted that this will remove it, clicked OK and crash.  Log below.  Looks like the code doesn't like a zero size array and gets all upset when the array is emptied.
`[18:22:27 INF] New app instance is being launched on Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020`
`[18:22:27 INF] DB Directory: /home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/bin/Debug/netcoreapp3.1`
`/home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/bin/Debug/netcoreapp3.1: True`
`[18:22:29 INF] IPC server starts listening... `
`[18:22:30 INF] DB Directory: /home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/bin/Debug/netcoreapp3.1`
`/home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/bin/Debug/netcoreapp3.1: True`
`[18:22:30 INF] DB Directory: /home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/bin/Debug/netcoreapp3.1`
`/home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/bin/Debug/netcoreapp3.1: True`
`[18:22:30 INF] IdentityManager initialized.`
`[18:22:30 INF] App initialization completed!`
`[18:22:30 INF] NotifyIcon implementation available, setting up NotifyIcon`
`[18:22:31 INF] SystemEventNotifier polling task started`
`[18:22:31 INF] QuickPass system event handlers initialized.`
`[18:22:31 INF] QuickPassManager initialized.`

`(SQRLDotNetClientUI:6804): LIBDBUSMENU-GLIB-WARNING **: 18:22:32.432: About to Show called on an item wihtout submenus.  We're ignoring it.`
`[18:25:14 INF] IPC client connected!`
`[18:25:14 INF] IPC server received data: sqrl://<URL>/wp-admin/admin-post.php?action=sqrl_auth&nut=myS9IOquvRi4MhAG86QglrkW5t3aHLnD&can=aHR0cHM6Ly9hYW1hYmlsZS5tZS51aw`
`Http Listening`
`[18:25:14 INF] IPC server showing main window!`
`[18:25:14 INF] Restoring main window`
`Processing Request`
`Got Gif request`
`Responded to Gif request`
`Http Listening`
`Processing Request`
`Got CPS Request`
`Holding here till CPS is Ready`
`Unhandled exception. System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')`
`   at System.String.Substring(Int32 startIndex, Int32 length)`
`   at SQRLDotNetClientUI.Models.QuickPassManager.SetQuickPass(String password, Byte[] imk, Byte[] ilk, SQRLIdentity identity, IProgress'1 progress, String progressText) in /home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/Models/QuickPassManager.cs:line 236`
`   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)`
`   at Avalonia.Threading.JobRunner.RunJobs(Nullable'1 priority)`
`   at Avalonia.X11.X11PlatformThreading.CheckSignaled()`
`   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)`
`   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)`
`   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)`
`   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)`
`   at SQRLDotNetClientUI.Program.Main(String[] args) in /home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/Program.cs:line 78`

**Comment by dxcSithLord** [comment]
Re-launch and the Identity is still loaded, deleted and no crash this time:
dotnet run
[18:33:22 INF] New app instance is being launched on Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020
[18:33:22 INF] DB Directory: /home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/bin/Debug/netcoreapp3.1
/home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/bin/Debug/netcoreapp3.1: True
[18:33:23 INF] IPC server starts listening...
[18:33:24 INF] DB Directory: /home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/bin/Debug/netcoreapp3.1
/home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/bin/Debug/netcoreapp3.1: True
[18:33:24 INF] DB Directory: /home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/bin/Debug/netcoreapp3.1
/home/sithMagic/src/SQRLDotNetClient/SQRLDotNetClientUI/bin/Debug/netcoreapp3.1: True
[18:33:24 INF] IdentityManager initialized.
[18:33:24 INF] App initialization completed!
[18:33:24 INF] NotifyIcon implementation available, setting up NotifyIcon
[18:33:24 INF] SystemEventNotifier polling task started
[18:33:24 INF] QuickPass system event handlers initialized.
[18:33:24 INF] QuickPassManager initialized.

**Comment by dxcSithLord** [comment]
Title wrong - crash when Quick Pass is used (note that the SQRL url isn't working on click, so opened in new window.

**Comment by alexhauser** [comment]
@dxcSithLord I can see what's happening, there is a sanity check missing for the `password` parameter in `QuickPassManager.SetQuickPass()`. I'll post a fix shortly.

Thanks for reporting!
