### ISSUE TITLE
New Identity - Variation in output

### ISSUE THREAD

**Issue by ghost** [sqrldev/SQRLDotNetClient#177]
When you create a new identity and have successfully entered the Rescue Code you are presented with a dialog to Export Identity. There are two options the second talks about the Super secure Rescue Code. If you choose that option the output is the pdf which is headed _username_ SQRL Identity.
This has three sections of descriptive text surrounding the QR code and the textual version of the code. The textual version of the code is shorter than the output if you selected the NON super secure rescue code but the descriptive text is identical. Either the textual output is wrong or the descriptive text should show a difference.
 think it is the latter as the super secure rescue code must be including the rescue code in the textual output.

**Comment by alexhauser** [comment]
You're right @MacNala, the descriptive text should be changed according to the chosen export option. This needs to be fixed. 

Great catch, thank you!
