### ISSUE TITLE
Export Identity looping back

### ISSUE THREAD

**Issue by ghost** [sqrldev/SQRLDotNetClient#178]
In the creation of a new identity when you get to the choice of secure or super secure. The Back button loops back to the verify new identity and then again the back button loops back to the Export Identity dialog. this should not be allowed the second back button should cancel the creation and return to the Create New Identity step.

**Comment by ghost** [comment]
Additional problem associated with #178
Closing the erroneous Export Identity and attempting to restore from SQRL icon reshows the Export Identity dialog. It should show the initial Sqrl Client Identity actions.

**Comment by alexhauser** [comment]
Thanks for the report Alan, we'll look into it!
