### ISSUE TITLE
Importing Identity - no difference between *.sqrl and *.sqrc

### ISSUE THREAD

**Issue by ghost** [sqrldev/SQRLDotNetClient#179]
_I think there should be a difference between the importing an identity from a file with the extension *.sqrc and *sqrl.
There doesn't seem to be in both cases you are asked for the Rescue code.
I thought the one with *.sqrc was including the rescue code and the *.sqrl was without it.

**Comment by alexhauser** [comment]
Yep, we should definitely allow importing `*.sqrl` files without requiring the rescue code. Again, great catch, Alan!

**Comment by alexhauser** [comment]
@josegomez, tackling this one next!
