### ISSUE TITLE
Linux-Arm-32bit-Out of memory error

### ISSUE THREAD

**Issue by dxcSithLord** [sqrldev/SQRLDotNetClient#187]
Running on Raspbian 32bit ARM - compiled from source.
Attempting to create New ID.  Rescue code generated and saved to PDF, new name and password entered for ID.  Click to create the ID and "Out of memory error" is displayed.  Log from "dotnet run" attached:
[Create_New_SQRL_ID_Failure.log](https://github.com/sqrldev/SQRLDotNetClient/files/4609211/Create_New_SQRL_ID_Failure.log)
Further debug will be performed to try and pin down.  I will also update code to latest, but don't expect this bug to go away that easy.

**Comment by alexhauser** [comment]
@dxcSithLord, the system is simply out of main memory (RAM).

The fact that this happens on the call to `scrypt` reinforces the point, since `scrypt` is a "memory-hard" key derivation function, which means it deliberately uses RAM to thwart the use of specialized hardware implementations.

What Raspi model are you running on, and how much main memory (RAM) do you have?

**Comment by dxcSithLord** [comment]
Pi 4B with 4G RAM, 1.9G Free when the process is running.  How much memory does enscript require?  
I am going to run strace on the process later to get more details - it should show what it is trying to claim.  There may also be a kernel limit on how much memory a user space application can grab, I will check that too.
Is there a test that I can run to help debug this, SQRLUtilTests perhaps?  If so, how can I test the enscript component works OK on the Pi, by itself?

**Comment by alexhauser** [comment]
> 1.9G Free when the process is running. How much memory does enscript require?

That does sound like plenty. SQRL's default `scrypt` parameters specify a memory consumption of 16MB. So there must be something else going on.

**Comment by dxcSithLord** [comment]
I found where the problem is, more digging tomorrow:
from SQRLUtilsLib/SQRL.cs around line 240 (I added some debug statements):
Log.Information($"Running EnScryptTime for {secondsToRun} seconds");

            byte[] passwordBytes = Encoding.ASCII.GetBytes(password);
            DateTime startTime = DateTime.Now;
            byte[] xorKey = new byte[32];
            int count = 0;

            Log.Information($"Running EnScryptTime: debug 1  ");

            return await Task.Run(() =>
            {
                count = 0;
                while (Math.Abs((DateTime.Now - startTime).TotalSeconds) < secondsToRun)
                {
                    Log.Information($"Running EnScryptTime: debug 2  ");
                    byte[] key = PasswordHash.ScryptHashLowLevel(passwordBytes, randomSalt, logNFactor, 256, 1, (uint)32);

                    Log.Information($"Running EnScryptTime: debug 3  ");
                    if (count == 0)

The logging generated the debug 1 and debug 2, but not the debug 3 lines.  More tomorrow.

**Comment by josegomez** [comment]
Right it’s running the scrypt algorithm that is causing the memory limit which makes sense

**Comment by dxcSithLord** [comment]
What is different between libsodium 1.0.17-1 and 1.0.18?  The published one for Raspbian (form apt packager) is the earlier version, but I see the code is using a later version.  I don't expect this to be the problem, just getting info).  I am also going to try this on Debian 32bit, to see if it is specific to ARM or 32bit.

**Comment by alexhauser** [comment]
> What is different between libsodium 1.0.17-1 and 1.0.18? The published one for Raspbian (form apt packager) is the earlier version, but I see the code is using a later version.

Without having checked, I don't expect the version difference to be the cause of the troubles you're seeing, either.

> I am also going to try this on Debian 32bit, to see if it is specific to ARM or 32bit.

Yep, good idea. Since we've never published nor tested the client for 32-bit architectures, it might very well be a problem with libsodium on 32-bit in general. 

Looking forward to your testing results.

**Comment by dxcSithLord** [comment]
So I have an up to date debian 10 (32 bit) "Buster", but it does not appear that dotnet sdk is available for linux 32bit (x86).  I will need to think on this and look into how to get more logging out of the code.  My feeling is that there is a data type, or assumption that is failing when running 64bit design on 32 bit OS.  I can't see anything obvious in the code, so pinning it down is next.  My learning curve on dotnet c# is about to go exponential.

**Comment by dxcSithLord** [comment]
Found how to build dotnet sdk from source, so I will try that.

**Comment by alexhauser** [comment]
@dxcSithLord, are you still working on this, or shall we close this issue?

**Comment by dxcSithLord** [comment]
I would need to go into a debugger to examine all the parameters, but this looks like there is a parameter that goes above a value that goes out of memory on 32bit, but not 64 bit 2^33?  I cant progress this at the moment, so happy for it to be closed. If i need to I can reopen, when i have fix.
