### ISSUE TITLE
SQRL scheme registration for Mac and Linux

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#19]
Registering the SQRL:// scheme for Mac and Linux takes an act of God... I haven't been able to get it to work.

**Comment by alexhauser** [comment]
Have you seen this, @josegomez?
https://github.com/sqrldev/Linux-GRC-SQRL-Installer-Script/blob/master/sqrl-install.sh

Especially this part:

```sh
# Everything should be good to go! We'll create the
# .desktop file in the current directory and install
# it.

echo "[Desktop Entry]" > grc-sqrl.desktop
echo "Name=SQRL" >> grc-sqrl.desktop
echo "Type=application" >> grc-sqrl.desktop
echo "Exec=wine '$sqrlexe' %u" >> grc-sqrl.desktop
echo "Categories=Internet" >> grc-sqrl.desktop
echo "Terminal=false" >> grc-sqrl.desktop
echo "MimeType=x-scheme-handler/sqrl" >> grc-sqrl.desktop
xdg-desktop-menu install grc-sqrl.desktop
```

This is for enabling the sqrl:// scheme for the GRC client under Wine, but it sould give you an idea of how it should work.

Hope it helps.
Alex

**Comment by josegomez** [comment]
Ok added Linux Installer script with commit d340b95

**Comment by alexhauser** [comment]
Nice, so is the `sqrl://` scheme working now, @josegomez?

**Comment by josegomez** [comment]
yes @alexhauser  on Linux if you use that installer script [Here](https://github.com/sqrldev/SQRLDotNetClient/blob/master/Installers/Linux/SQRL.sh)
It should register the scheme and everything.

Working on the Mac version now
