### ISSUE TITLE
Change default install path on Linux

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#191]
### Description:
On Linux, we currently install the client into a subdirectory named `SQRL` within the user's home directory, so for example `/home/alex/SQRL`.

This is exactly the directory that we end up with when moving the database to "user space" on Linux, since `Environment.SpecialFolder.MyDocuments` maps tp the user's home folder (e.g. `/home/alex`) , and our `PathConf.DefaultClientDBPath` therefore also points to `/home/alex/SQRL`.

This is a mess - since this defeats our desired separation of application and user data, and even worse, uninstalling the client would wipe the db.

I would therefore suggest to change the default install path for the app on Linux, to either
- `/opt/SQRL` or
- `/usr/share/SQRL`

These are the recommended directories according to
https://askubuntu.com/questions/27213/what-is-the-linux-equivalent-to-windows-program-files
and
https://i.stack.imgur.com/BlpRb.png

What do you think, @josegomez?

**Comment by josegomez** [comment]
I would lean towards more /usr/bin or /usr/local/bin than /opt 
opt appears to be more of a support file storage location and less executable.
But frankly it doesn't matter, as long as we keep it consistent.
I'll defer the call to you

**Comment by alexhauser** [comment]
@josegomez, `/usr/bin` is usually reserved for stuff that comes through the package manager.

As for `/usr/local/*`:
> /usr/local is a place to install files built by the administrator usually by using the make command (eg: ./configure; make; make install). The idea is to avoid clashes with files that are part of the operating systems which would either be overwritten or overwrite the local ones otherwise. eg. /usr/bin/foo is part of the OS while /usr/local/bin/foo is a local alternative.

Whereas `/opt`:
> ... /opt is a directory where to install unbundled packages, each in its own subdirectory. They are already built whole packages provided by an independent third party software distributor. 

Sounds like `/opt` would be the proper place to put it according to the `Filesystem Hierarchy Standard` linked below. This is also where I was leaning towards.

For reference, see:
http://www.extradrm.com/?p=2266 or
https://www.pathname.com/fhs/pub/fhs-2.3.html

So if you don't mind, I would go for `/opt/SQRL` as the new default install location on Linux.
