### ISSUE TITLE
archlinux crashes

### ISSUE THREAD

**Issue by markboston3502191** [sqrldev/SQRLDotNetClient#20]
the app crashes when i try to import my sqrl id.

**Comment by josegomez** [comment]
Where are you importing from? Grcs client?

**Comment by alexhauser** [comment]
@markboston3502191, any chance of providing a little more info regarding the crash?

**Comment by alexhauser** [comment]
Going to close this one, since no feedback was provided and the import code has changed meanwhile anyway. @markboston3502191, if this still happens using the latest version from master, please re-open and let us know.
