### ISSUE TITLE
[MacOS] Client not completing authentication

### ISSUE THREAD

**Issue by ScottyZA** [sqrldev/SQRLDotNetClient#210]
Client version: SQRLDotNetClientUI version 0.1.2.0
OS: Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64

Testing on the SQRL demo page: https://sqrl.grc.com/demo.

My client is receiving the NUT from sqrl://sqrl.grc.com but does nothing afterwards.

Logs from /Applications/SQRL.app/Contents/MacOS below:

[INF] Handling Open URL Event
[INF] Got URL:sqrl://sqrl.grc.com/cli.sqrl?nut=xxxxxxxxxxx
[INF] Open URL Data: sqrl://sqrl.grc.com/cli.sqrl?nut=xxxxxxxxxxx
[INF] Restoring main window
[INF] Hiding main window instead of closing it

**Comment by ScottyZA** [comment]
Apologies, I was using the Brave browser. Once I removed the built in blocking feature, the SQRL sign up worked.

**Comment by alexhauser** [comment]
Thanks for letting us know, @ScottyZA!
