### ISSUE TITLE
Is it possible to integrate SQRL with webauthn? (question or feature)

### ISSUE THREAD

**Issue by ghost** [sqrldev/SQRLDotNetClient#217]
Hi all!

## Description
Is it possible to integrate SQRL with webauthn? (question or feature)

## Related Links
- https://github.com/Jaaap/SQRL/issues/20
- https://community.bitwarden.com/t/steve-gibson-from-grc-and-sqrl/26638
- https://community.bitwarden.com/t/sqrl-identity/273
- https://community.bitwarden.com/t/sign-in-using-qr-code-without-master-password/15727
- https://community.bitwarden.com/t/temporary-master-password/9725
- https://fidoalliance.org/how-fido-works/
- https://doubleoctopus.com/security-wiki/protocol/fast-identity-online/
- https://fidoalliance.org/
- https://www.grc.com/sqrl/sqrl_explained.pdf
- https://www.grc.com/sqrl/sqrl_cryptography.pdf
- https://www.grc.com/sqrl/sqrl_on_the_wire.pdf
- https://www.grc.com/sqrl/sqrl_operating_details.pdf
- https://www.grc.com/sqrl/SQRL_Explained.pdf
- https://github.com/w3c/webauthn/issues/1786
- https://www.yubico.com/authentication-standards/webauthn/
- https://github.com/Novators/sqrl-spec/issues/43

**Comment by raphael-louis-andress** [comment]
Hi all!

**Comment by josegomez** [comment]
Closing as Spam
