### ISSUE TITLE
Implement identity settings

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#23]
Implmement the UI and logic for changing identity settings.

**Comment by josegomez** [comment]
When you get to this let me know if you want a quick primer on Avalonia and how I setup the UI project. The Avalonia MVVM model etc can be kinda weird if you aren't familiar with it it's modeled after WPF so if you are familiar with that it should mostly translate but there are some quirks

**Comment by alexhauser** [comment]
Thanks @josegomez, I'm going to work on this next, I have some MVVM and also some WPF experience so I guess it should be fine, but I'll definitely ping you if I get stuck somewhere!
