### ISSUE TITLE
Enhance CPS Behavior

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#38]
Right now CPS works but its pretty rudimentary for instance if CPS is running and a SQRL login action is started the browser hangs (as it should) waiting for a CPS Response.
However if the SQRL client closes or crashes the browser just goes to 404

We should handle that gracefully on exit any pending CPS requests need to be redirected to the cancel URL and things of that sort

**Comment by alexhauser** [comment]
Yeah... I have a local branch where I've already pimped the CPS server a little, like giving it `Start` and `Stop` methods and such. 

Also, I have implemented the cancel behaviour on the Android client, so I have some assets readily available, like the HTML page that we can show upon cancellation, which already contains some JavaScript to redirect back after a while. 

I'll dig up the stuff and provide it here, maybe it will be useful.

**Comment by alexhauser** [comment]
Ok, so here is the link to the HTML that the Android client pushes to the browser if CPS gets cancelled but no cancellation URL is given:

https://github.com/kalaspuffar/secure-quick-reliable-login/blob/master/app/src/main/assets/cps_cancelled.html

... which looks something like this:

![cps_cancelled](https://user-images.githubusercontent.com/4005543/75612524-7a7a3100-5b24-11ea-9ed3-ae0f0657cfc3.PNG)

**Comment by josegomez** [comment]
I'll take this next @alexhauser

**Comment by josegomez** [comment]
Fixed by #128
