### ISSUE TITLE
Add support for Indexed Secret / Secret Index

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#4]
Currently the library doesn't support secret  / secret index. Most of the pieces are there and could probably be done but it would be nice to support it directly on any of the calls.

I'm moving my focus to the Client UI, so this is just an enhancement request for now.

**Comment by alexhauser** [comment]
I'm about to implement the basic library part and the corresponding tests.

**Comment by alexhauser** [comment]
@josegomez, should we leave this issue open unil the protocol part is implemented, or do you find this issue is resolved?

**Comment by josegomez** [comment]
Let's keep it open until we integrate it into the protocol. I'll work on that next.

**Comment by josegomez** [comment]
Added and Merged.
