### ISSUE TITLE
Implement Re-Key Identity Feature

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#41]
ReKey Identity Feature needs to be implemented. Most of the logic exists in the SQRLConsoleTester project we just need to implement it in the UI.

**Comment by josegomez** [comment]
Doing this one next @alexhauser

**Comment by alexhauser** [comment]
@josegomez, just letting you know that I am working on a `ProgressDialog` for #61 that I plan to be reusable for all views/viewmodels that need to display progress.

This should avoid needing to place a `ProgressBar` into each and every view. If it works out well (and obviously if you like it as well and agree to the plan), I plan on backporting this to all the views that currently display progress "their own way".

I will show off how it will look like as soon as I have something.

**Comment by josegomez** [comment]
Sounds good @alexhauser keep in mind that for a couple of screens I've done parallel processing (decrypting block 1 and block 2 at the same time) and it used to different progress bars 

Not that we have to do this but just think if there's a good option for that scenario
We can always do it sequentially though no big deal

**Comment by alexhauser** [comment]
@josegomez, I actually already have plans for that scenario: It will be possible to add an arbitrary number of `IProgess` objects to the dialog! 😀

**Comment by josegomez** [comment]
Implemented in #67
