### ISSUE TITLE
Decryption of block 2 fails

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#50]
If you follow these steps:

- Import an identity using rescue code XYZ, set new password
- Use this identity to lock your account on GRC's demo page
- Try to unlock the account using the same identity

you will find that the same rescue code XYZ won't decrypt block 2.
Something is wrong here, haven't looked at it yet, but wanted to note it down.

**Comment by josegomez** [comment]
So I had a similar issue before and it was we weren't "cleaning" the rescue code (removing dashes etc) in some places. I wonder if that's the issue here?
Maybe on import we are not cleaning up the rescue code when we re-encrypt, then when we try to decrypt we do clean it and it fails.

**Comment by alexhauser** [comment]
Yeah, probably something trivial like that. Going to investigate a little later.

**Comment by alexhauser** [comment]
Fixed in #56.
