### ISSUE TITLE
Add universal progress dialog

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#64]
As discussed shortly in #41, I'm implementing a `ProgressDialog` to avoid having to implement progress bars and reactive properties for it in each and every `ViewModel` that needs progress to be displayed.

Using the progress dialog is very simple:

```C#
// You can either create a list of progress items and pass it in the constructor...
var progressList = new List<Progress<KeyValuePair<int, string>>>() { progress1, progress2 };
ProgressDialog pd = new ProgressDialog(progressList);

// ...or add them as you need
pd.AddProgressItem(progress3);

// You can influence the behaviour of the dialog:
pd.HideFinishedItems= true; // Will hide each progress item when it reached 100%
pd.HideEnqueuedItems = true; // Will hide each progress item until it receives its first ProgressChanged event

// Then just show the dialog async
pd.ShowDialog(_mainWindow);

// Do some stuff here, await the tasks etc.
// ProgressDialog will be displaying the progress

// Then, just close the progress dialog
pd.Close();

```

I have a working prototype running, it currently looks something like that:
(showing an operation with 3 progress "items" enqueued)

![ProgressDialog_Multiple](https://user-images.githubusercontent.com/4005543/76931143-540c1200-68e8-11ea-9552-0d41a7258ee1.gif)

@josegomez, do you like the idea/implementation? Shall I go forward with it?

**Comment by josegomez** [comment]
This is very nice @alexhauser !

**Comment by josegomez** [comment]
Beautiful work @alexhauser great job!
