### ISSUE TITLE
Add PDF support

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#72]
Add support for exporting the textual identity as well as the rescue code to a PDF file.

Progress:
- [x] Identity
- [ ] Rescue Code (implemented core functionality but not exposed in the UI yet)

I'm going for this one next, @josegomez!

**Comment by josegomez** [comment]
you are on a roll @alexhauser !Are you in quarentine?
We are it's been rough to write code with kids all over the house lol

**Comment by alexhauser** [comment]
I am - sort of at least. :)

It's not quarantine actually, but there has been a curfew in place here in Tirol/Austria for almost two weeks now! So I enjoy the coding excercises in between home office, doing the chores in the household, taking care of my wife (she has a medical condition) and playing teacher for my daugther.

**Comment by josegomez** [comment]
> I am - sort of at least. :)
> 
> It's not quarantine actually, but there has been a curfew in place here in Tirol/Austria for almost two weeks now! So I enjoy the coding excercises in between home office, doing the chores in the household, taking care of my wife (she has a medical condition) and playing teacher for my daugther.

Ah makes sense, glad that you are able to still work from home and such. I work from home all the time but normally the kids (3) are in school / day care. But for the last 2 weeks they've been home so I've had to do the home schooling thing while trying to continue working... It has been... FUN! hehe!

Anyways great job man thanks!

**Comment by alexhauser** [comment]
Yeah, it's a challenge for a lot of people right now. I guess we are still lucky, only being a little busier than usual! :)

Thanks for the appreciation, Jose!

**Comment by alexhauser** [comment]
Reopening this one since there is some more work to do exposing the existing rescue code document functionality.
