### ISSUE TITLE
Reconsider Authentication Flow?

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#73]
So I've been thinking a little about the authentication flow of the client and I'm wondering if what we have is good as is or if we should re-consider the flow / design o fit (logic)

Currently when an Authentication request is received flows as follows

1. Prompt use for Password and Options (this is good)
2. User clicks (OK , Login)
2.1 Decrypt Block 1 using password
2.2 Create Site Key
2.3 Generate prior site keys and their related KeyPairs
3. Issue a query command (this is where some of the questions come to mind for me)
3.1 If Query Command Fails with Transient Error (re-try 3 times)
4. If the query command failed, show error and abort
5. If Query Command Succeeded and we couldn't find a match
5.1 Handle create new Account (one issue here is if the user selected remove, or disable we are still handling create new account... maybe need to reconsider?)
5.2 If the user agreed to a new account Issue Ident (Authenticate) regardless of chosen Action
6. If Prior Id Matches (re-key occurred)
6.1 Handle ID replacement (again if user selected, remove or disable we are still doing this... is that ok?)
6.2 Proceed with Authentication (ignoring Disable, Remove command)
7. If current ID matches
7.1 Check if Ask was... (well asked) if so Handle Ask Dialog (again we are ignoring the Disable, Remove command at this point and handling ask... should we?)
7.2 If SQRL returns as Disable
7.2.1 Handle Disable prompt ask if they want to continue etc
7.3 Handle Selected Action (Login, Disable, Remove)

This is the current flow as Implemented. It assumes 1 successful Query (or all else fails) it also handles Ask, and New Accounts before handling "Action"
New Account ignores any selected action and just creates a new account (if the user agrees)
New Account (if created) always continues with an Ident Command and Authenticates the user... (is that ok?)
Ask is also handled regardless of user Action (Login, Disable, Remove)... maybe that's ok?

**Comment by josegomez** [comment]
@alexhauser  any thoughts if we need to change any of this logic?

**Comment by alexhauser** [comment]
@josegomez, since I don't really have a lot of experience when it comes to the protocol part of the SQRL spec, I'll have to look into this more closely to even get a feeling for it. So it might take a while before you get an educated opinion from me on this topic. Sorry!

**Comment by josegomez** [comment]
I think we are ok for now we can come back and re-consider this later if needed. Closing for  now
