### ISSUE TITLE
Add Auto-Update Logic to SQRL Client Itself

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#74]
The installer can update SQRL, but SQRL itself needs to be made aware there is a new version so it can invoke the installer to update itself.

**Comment by alexhauser** [comment]
Yes, we definitely need this!

**Comment by josegomez** [comment]
Working on this @alexhauser 
Trying to figure out what the best strategy is here, should we check for a new version once a day? or when the program first opens? (both)?

**Comment by alexhauser** [comment]
Yep, I guess both would be appropriate. 👍

Are you going to pull out the version check/Github API into its own library that both the installer and the client use, or does the client need to do something different anyway, so that we won't be duplicating code between the two?

**Comment by josegomez** [comment]
> Yep, I guess both would be appropriate. 👍
> 
> Are you going to pull out the version check/Github API into its own library that both the installer and the client use, or does the client need to do something different anyway, so that we won't be duplicating code between the two?

So im writing the "Version" into a file at install time
Then going to check the github api to see if a "new" (different) vesion is available. The code may be similar... I'll double check if I can put it in a library

**Comment by josegomez** [comment]
Added with #81 including the GitHub lib

**Comment by josegomez** [comment]
Fixed on #81
