### ISSUE TITLE
Change Deployment Strategy for SQRL Client

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#75]
SQRL Client until now has been deployed as a Single Package Application from .net core
This is nice, however it automatically decompresses itself into a secret / special folder which includes the SQL Lite DB files.
This can be an issue if we upgrade and accidentally delete things or can cause confusion.

Now that we have a Single Package Application (installer) we should update the process to use a simple zip approach to deploy the actual SQRL Client package, this would allow us to 
a) Know and understand where the SQRL files are actually stored
b) Backup and keep and make sure we protect the Db file.
c) We could deploy only the changed files (Diff) which would make the updates smaller and more compact.

**Comment by alexhauser** [comment]
Amen to all the above!

**Comment by josegomez** [comment]
Fixed on #77
