### ISSUE TITLE
Next button on left, Cancel on Right

### ISSUE THREAD

**Issue by jwadamson** [sqrldev/SQRLDotNetClient#79]
The new identity has the "next" button on the left side of the dialog.
That arrangement is a little off putting and potentially error prone for LTR languages like english.

**Comment by josegomez** [comment]
Thanks Jeff, on it!

**Comment by alexhauser** [comment]
@jwadamson, you must be running an older version of the app.
I've already fixed this a while ago:

![new_identity](https://user-images.githubusercontent.com/4005543/78454980-fb849500-769b-11ea-8c8a-d354d8eb8984.PNG)

Can I close this one or have you spotted this problem anywhere else as well?

**Comment by jwadamson** [comment]
Strange. I had just downloaded the osx build from the link at the bottom on https://github.com/sqrldev/SQRLDotNetClient

**Comment by josegomez** [comment]
Oh yeah that's an old one go to the releases tab instead.
I'll fix the read me
