### ISSUE TITLE
Fix code duplication between projects

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#86]
The different UI projects should not duplicate common code like all the `AvaloniaExtensions` (`CopyPasteTextBox`, `LocalizationExtension`...) but instead reference a central implementation of them in a common library.

For example, the `LocalizationExtension` was heavily enhanced in the client UI project, and the installer still has a bare-bones copy-n-paste version of that extension from the early days.

I would therefore suggest creating a `SQRLCommonUI` library project where all the common functionality should be placed.

Thoughts, @josegomez?

**Comment by alexhauser** [comment]
I'm experimenting with this right now, @josegomez.

**Comment by josegomez** [comment]
Sounds great
