### ISSUE TITLE
Textual identity export should only export block type 2

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#92]
I noticed that the textual export is huge compared to other clients. I looked at the export code and found that we currently export the full identity (all block types). 

According to the spec, we should only be using block type 2 for the textual identity version.

**Comment by josegomez** [comment]
@alexhauser  Shouldn't it also export block type 3? Otherwise you lose all your prior identities

**Comment by alexhauser** [comment]
> @alexhauser Shouldn't it also export block type 3? Otherwise you lose all your prior identities

Yikes, thanks for catching that one @josegomez, of course! Going to fix this!
