### ISSUE TITLE
[linux] Issues from SQRL.grc.com thread.

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#96]
- [x] (1) Download is not executable, I had to "chmod +x" to get it to run.
(WONTFIX)
- [x] (2) I ran as an ordinary user, and it installed OK.
- [x] (3) On the install screen, the "Next" button is right at the edge of teh window, or might even overlap it slightly. The progress bar seemed to go off the window.
- [x] (4) Minor typo on main SQRL screen - "Impot identity" should be "Import"
- [x] (5) Help/About does not respond with version number.

see: https://sqrl.grc.com/threads/linux-testing-feedback.1109/post-9271

**Comment by alexhauser** [comment]
3 should already be fixed by my latest PR.

**Comment by alexhauser** [comment]
Just fixed 4 in #100.
5 is known (simply not implemented yet), will get to that eventually.

**Comment by alexhauser** [comment]
@josegomez, 

as for (1), if you `chmod +x` on a linux box before uploading, is the download still not executable?
As for (2), is this an issue? Actually sounds like a feature ;-)

I'm working on (5).

**Comment by alexhauser** [comment]
(5) is addressed in #106.

**Comment by josegomez** [comment]
@alexhauser I haven't tried I dev on windows so I can't chmod before upload at least not easily... Maybe I can use WSSL for that.

**Comment by josegomez** [comment]
yeah (2) is fine that's what we want.

**Comment by alexhauser** [comment]
> @alexhauser I haven't tried I dev on windows so I can't chmod before upload at least not easily... Maybe I can use WSSL for that.

Sounds like a plan! Would be great if you could try it out sometime @josegomez, since this is the last item standing for this issue.

**Comment by josegomez** [comment]
@alexhauser I'll give it a shot.

**Comment by alexhauser** [comment]
Any news on this front, @josegomez? It would be cool if we could close this one, since it would be one more step towards our v0.1.2 milestone.

**Comment by dxcSithLord** [comment]
Note on "chmod +x", that will work, but you would still need to provide the path, best to use full path.

**Comment by alexhauser** [comment]
@dxcSithLord, fyi this is not about issuing `chmod +x` after the download, which would obviously work, but how we can avoid this being necessary. 

The question is if the `chmod +x` will stick if issued before uploading the binary to Github.

**Comment by dxcSithLord** [comment]
No that won't work.  The permissions on Linux/Unix are based on a default file creation permissions default, which doesn't include execute permissions.  That would be bad from a security point of view if every file were by default executable.
However, if the files were in a tar file, with the permissions set, that would work, as tar can retain file permissions.  The other edge of that sword is that ALL permissions are retained, so the file permissions may look like 
-r-xr-xr-x 1001 1001 123456 SQRLDotNetUI
where the 1001 is the UID of the user that you used - if that UID exists, it will map to that user, which generally is not what you want.
If this is what you want, don't use an exe file, use a bash/shell script file to run the commands.  That doesn't need execute permission if prefixed with "/bin/bash".  The script can (many already exist in github) determine what Linux OS type it is running on and can handle whatever packaging or directory structure is on the system.
If I get a chance this week, I will try running the above dotnet on a raspberry pi, and perhaps work out (pointers again would be useful) what the installer is attempting to achieve.  I can put that into a bash script if needed.

**Comment by josegomez** [comment]
I tested it and it didn't work (as suspected)

@alexhauser this is a wont fix nothing we can do unless we want to switch to a tar like @dxcSithLord mentioned at this point I don't know if that would be acceptable and we have a ton of other changes to go through so I'd say shelf this one for now.

The instructions state to run chmod a+x... and frankly if you are running linux you should know how to do this hehe!

Thoughts?

**Comment by alexhauser** [comment]
I agree, closing this one!
