### ISSUE TITLE
Window Positioning Issue on Mac and Linux

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#97]
So after much troubleshooting there is just no real / reliable way to have a window positioned properly across the platforms.
![image](https://user-images.githubusercontent.com/420837/78461575-587e4c00-7698-11ea-90c7-0dc12f6db659.png)
I even reached out to the avalonia folks to no avail.

I did have an idea, what if we make the progress "dialog" less of a dialog and we just replace the main content (like we do everything else)
When the dialog finishes we just put the content back and display errors etc as needed.

Thoughts? @alexhauser  I can put together an example if it would help.

**Comment by alexhauser** [comment]
Sure @josegomez, I wouldn't mind dumping the dialog window for a UserControl.

**Comment by josegomez** [comment]
I'll give it a shot, we are still stukc with the messageboxes but there's less of that. I think though we could also replace the stuff there...not sure that would work nicely though

**Comment by josegomez** [comment]
This was implemented in #98
